version: 2
updates:
  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "Into-The-Grey"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Git submodules updates
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "gitsubmodule"
    reviewers:
      - "Into-The-Grey"
