name: Build L.I.S.A MDBook

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  actions: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      INSTALL_CLEAN: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Move SUMMARY.md and custom theme files to correct locations
        run: |
          set -e
          mkdir -p src
          mkdir -p theme

          # Find SUMMARY.md not already in src/ and move it
          FOUND_SUMMARY=$(find . -type f -iname SUMMARY.md ! -path "./src/SUMMARY.md" | head -n 1 || true)
          if [ -n "$FOUND_SUMMARY" ]; then
            echo "Found SUMMARY.md at $FOUND_SUMMARY. Moving to src/SUMMARY.md"
            mv -f "$FOUND_SUMMARY" src/SUMMARY.md
          fi

          # Move custom.js and custom.css if not already in theme/
          for THEMEFILE in custom.js custom.css; do
            FOUND_THEME=$(find . -type f -iname "$THEMEFILE" ! -path "./theme/$THEMEFILE" | head -n 1 || true)
            if [ -n "$FOUND_THEME" ]; then
              echo "Found $THEMEFILE at $FOUND_THEME. Moving to theme/$THEMEFILE"
              mv -f "$FOUND_THEME" theme/$THEMEFILE
            fi
          done

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Cache mdBook and plugin binaries
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-latest
          restore-keys: |
            ${{ runner.os }}-cargo-bin-

      - name: Install Rust toolchain and latest mdBook + plugins
        id: install-mdbook
        run: |
          set -e
          if ! command -v rustup >/dev/null; then
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          fi
          source $HOME/.cargo/env
          # Get latest mdbook version
          MDBOOK_VERSION=$(curl -s https://api.github.com/repos/rust-lang/mdBook/releases/latest | grep -oP '"tag_name":\s*"\K[^"]+')
          MDBOOK_VERSION=${MDBOOK_VERSION#v}
          echo "Latest mdBook version: $MDBOOK_VERSION"
          echo "MDBOOK_VERSION=$MDBOOK_VERSION" >> $GITHUB_ENV
      
          cargo install --force --version "$MDBOOK_VERSION" mdbook
      
          PLUGINS="mdbook-mermaid mdbook-toc mdbook-open-on-gh"
          echo "Checking plugins..."
          for plugin in $PLUGINS; do
            echo "Installing/upgrading $plugin ..."
            if cargo install --force "$plugin"; then
              echo "$plugin installed."
            else
              echo "WARNING: $plugin failed to install. It may be incompatible with mdBook $MDBOOK_VERSION. Skipping."
            fi
          done
      
          mdbook --version
          for plugin in $PLUGINS; do
            if command -v $plugin >/dev/null; then
              $plugin --version || true
            fi
          done

      - name: Setup mdBook theme, config, and plugins
        run: |
          mkdir -p theme
          echo 'window.addEventListener("DOMContentLoaded", () => {
            document.querySelectorAll("table").forEach(table => {
              table.style.overflowX = "auto";
              table.style.display = "block";
            });
            const fab = document.createElement("button");
            fab.textContent = "↑";
            fab.style.position = "fixed";
            fab.style.bottom = "2rem";
            fab.style.right = "2rem";
            fab.style.padding = "1rem";
            fab.style.fontSize = "1.5rem";
            fab.style.borderRadius = "50%";
            fab.style.boxShadow = "0 4px 8px rgba(0,0,0,0.2)";
            fab.style.zIndex = "9999";
            fab.style.border = "none";
            fab.style.background = "#007acc";
            fab.style.color = "white";
            fab.style.cursor = "pointer";
            fab.style.transition = "opacity 0.3s ease-in-out";
            fab.title = "Scroll to Top";
            fab.addEventListener("click", () => window.scrollTo({top: 0, behavior: "smooth"}));
            document.body.appendChild(fab);

            // Sidebar toggle for even more interactivity!
            const toggleSidebarBtn = document.createElement("button");
            toggleSidebarBtn.textContent = "☰";
            toggleSidebarBtn.style.position = "fixed";
            toggleSidebarBtn.style.top = "1rem";
            toggleSidebarBtn.style.left = "1rem";
            toggleSidebarBtn.style.zIndex = "10000";
            toggleSidebarBtn.style.background = "#007acc";
            toggleSidebarBtn.style.color = "#fff";
            toggleSidebarBtn.style.border = "none";
            toggleSidebarBtn.style.padding = "0.5rem 1rem";
            toggleSidebarBtn.style.fontSize = "1.5rem";
            toggleSidebarBtn.style.borderRadius = "10px";
            toggleSidebarBtn.style.boxShadow = "0 4px 8px rgba(0,0,0,0.1)";
            toggleSidebarBtn.style.cursor = "pointer";
            toggleSidebarBtn.title = "Toggle Sidebar";
            toggleSidebarBtn.onclick = () => {
              document.body.classList.toggle("sidebar-hidden");
            };
            document.body.appendChild(toggleSidebarBtn);
          });' > theme/custom.js

          echo 'html { scroll-behavior: smooth; }
          nav { touch-action: pan-y; }
          body { transition: background 0.3s, color 0.3s; }
          button:hover { filter: brightness(1.15); }
          .sidebar-hidden .sidebar {
            display: none !important;
          }
          .sidebar-hidden .content {
            margin-left: 0 !important;
            width: 100vw !important;
          }
          .admonition { border-left: 6px solid #007acc; margin: 1em 0; padding: 1em; background: #f8fafc;}
          .admonition-title { font-weight: bold; }' > theme/custom.css

          cat > book.toml << TOML
          [book]
          title = "L.I.S.A. Guide"
          authors = ["Into-The-Grey"]
          description = "A supercharged, interactive, local AI assistant documentation."
          multilingual = false

          [output.html]
          default-theme = "light"
          additional-js = ["theme/custom.js"]
          additional-css = ["theme/custom.css"]
          git-repository-url = "https://github.com/Into-The-Grey/Project-L.I.S.A-Guide"
          mathjax-support = true

          [preprocessor.toc]
          [preprocessor.mermaid]
          [preprocessor.open-on-gh]
          TOML

      - name: Build mdBook, generate PDF & ZIP
        run: |
          source $HOME/.cargo/env
          mdbook build
          sudo apt-get update && sudo apt-get install -y chromium-browser
          mkdir -p /home/runner/snap/chromium/common/.cache
          touch /home/runner/snap/chromium/common/.cache/desktop-runtime-date
          chromium-browser --headless --disable-gpu --no-sandbox --disable-dev-shm-usage --print-to-pdf=book.pdf book/index.html
          cd book && zip -r ../book.zip . && cd ..

      - name: Generate changelog, summary, and README
        run: |
          git fetch --prune --unshallow || true
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          NEW_TAG="v$(date +'%Y.%m.%d.%H%M%S')"
          if [ -z "$LAST_TAG" ]; then
            git log --pretty=format:"%h,%an,%s,%cd" --date=short > CHANGELOG.csv
          else
            git log $LAST_TAG..HEAD --pretty=format:"%h,%an,%s,%cd" --date=short > CHANGELOG.csv
          fi
          echo "# Summary" > src/SUMMARY.md
          echo "- [Introduction](README.md)" >> src/SUMMARY.md
          echo "- [Changelog](changelog.md)" >> src/SUMMARY.md
          echo "| Commit | Author | Message | Date |" > src/changelog.md
          echo "|--------|--------|---------|------|" >> src/changelog.md
          cat CHANGELOG.csv | while IFS=',' read -r hash author subject date; do
            echo "| [$hash](https://github.com/Into-The-Grey/Project-L.I.S.A-Guide/commit/$hash) | $author | $subject | $date |" >> src/changelog.md
          done
          echo "" > src/README.md
          echo "# Project Documentation" >> src/README.md
          echo "" >> src/README.md
          echo "This is the autogenerated documentation site for **Into-The-Grey/Project-L.I.S.A-Guide**." >> src/README.md
          echo "" >> src/README.md
          echo "- 📘 Built using **mdBook** ${{ env.MDBOOK_VERSION }}" >> src/README.md
          echo "- 🕒 Version: $NEW_TAG" >> src/README.md
          echo "- 🔗 View online: [GitHub Pages](https://Into-The-Grey.github.io/Project-L.I.S.A-Guide)" >> src/README.md
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add src/changelog.md src/SUMMARY.md src/README.md CHANGELOG.csv theme/* book.toml
          git commit -m "chore: update changelog, summary, README, and interactivity theme"
          git tag $NEW_TAG
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin $NEW_TAG
          git push origin main

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./book

      - name: Upload PDF version
        uses: actions/upload-artifact@v4
        with:
          name: book-pdf
          path: book.pdf

      - name: Upload ZIP version
        uses: actions/upload-artifact@v4
        with:
          name: book-zip
          path: book.zip

      - name: Upload Changelog CSV
        uses: actions/upload-artifact@v4
        with:
          name: changelog-csv
          path: CHANGELOG.csv

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy L.I.S.A MDBook to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
